site_name: "Dissonance: Unity Voice Chat"
repo_url: "https://github.com/Placeholder-Software/Dissonance"
repo_name: "Issue Tracker"
site_favicon: "dissonance.png"
google_analytics: ["UA-46722926-2", "dissonance.readthedocs.io"]
pages:
- Home: "index.md"
- Basic:
    - "Project Setup": "Tutorials/Getting Started.md"
    - "Basic VoIP Demo": "Tutorials/Basic VoIP.md"
    - "Networking Setup":
        - "UNet LLAPI": "Tutorials/Networking Setup - UNet LLAPI.md"
        - "UNet HLAPI": "Tutorials/Networking Setup - UNet HLAPI.md"
        - "Forge Networking": "Tutorials/Networking Setup - Forge Networking.md"
        - "Photon Networking": "Tutorials/Networking Setup - Photon Networking.md"
    - "Positional Audio": "Tutorials/Positional Audio.md"
    - "Rooms":
        - "Introduction": "Introduction To Chat Rooms.md"
        - "Global Chat": "Tutorials/Global Chat Room.md"
        - "Team Chat": "Tutorials/Team Chat Rooms.md"
        - "Area Chat": "Tutorials/Area Chat Room.md"
        - "Proximity Chat": "Tutorials/Proximity Chat.md"
        - "Direct Chat": "Tutorials/Direct Chat.md"
    - "Text Chat": "Tutorials/Text Chat.md"
- Intermediate:
    - "Audio Mixing For Voice": "Tutorials/Audio Mixing.md"
- Advanced:
    - "Writing A Network Integration": "Tutorials/Network Integration.md"
- Reference:
    - Components:
        - "Voice Broadcast Trigger": "Reference/Components/Voice Broadcast Trigger.md"
        - "Voice Receipt Trigger": "Reference/Components/Voice Receipt Trigger.md"
        - "Dissonance Comms": "Reference/Components/Dissonance Comms.md"
    - Networking:
        - "Network Packet Format": "Reference/Networking/Packet Format.md"
- "Frequently Asked Questions": "FAQ.md"
- "Glossary": "Glossary.md"