site_name: "Dissonance: Unity Voice Chat"
repo_url: "https://github.com/Placeholder-Software/Dissonance"
repo_name: "Issue Tracker"
site_favicon: "dissonance.png"
google_analytics: ["UA-46722926-2", "dissonance.readthedocs.io"]
pages:
- Home: "index.md"
- "Frequently Asked Questions": "FAQ.md"
- "Glossary": "Glossary.md"
- Basic:
    - "Project Setup": "Tutorial - Getting Started.md"
    - "Basic VoIP Demo": "Tutorial - Basic VoIP.md"
    - "Multiple Rooms": "Tutorial - Multiple Rooms.md"
    - "Positional Audio": "Tutorial - Positional Audio.md"
- Intermediate:
    - "Audio Mixing For Voice": "Tutorial - Audio Mixing.md"
- Advanced:
    - "Writing A Network Integration": "Tutorial - Network Integration.md"
- Reference:
    - Components:
        - "Voice Broadcast Trigger": "Reference/Components/Voice Broadcast Trigger.md"
        - "Voice Receipt Trigger": "Reference/Components/Voice Receipt Trigger.md"
    - Networking:
        - "Network Packet Format": "Reference/Networking/Packet Format.md"